server:
  port: ${SERVER_PORT:9999}
  tomcat:
    relaxed-query-chars: "[, ]"
    threads:
      max: 200
      min-spare: 10

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

spring:
  application:
    name: "eduverse-be"

  jackson:
    time-zone: "Asia/Ho_Chi_Minh"
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/eduverse_db}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:production}

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

application:
  client:
    url: ${CLIENT_URLS:http://localhost:5173}
  security:
    jwt:
      expiration: ${JWT_EXPIRATION:604800000}

eduverse:
  mail:
    from-email: ${MAIL_FROM:no-reply@eduverse.com}
    from-name: "EduVerse Support"

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:604800000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
  show-actuator: true

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.data.mongodb: DEBUG
    com.eduverse.eduversebe: DEBUG

socket-server:
  host: 0.0.0.0
  port: 8085

payment:
  client-url: ${CLIENT_URL}

  momo:
    partner-code: ${MOMO_PARTNER_CODE}
    access-key: ${MOMO_ACCESS_KEY}
    secret-key: ${MOMO_SECRET_KEY}
    api-endpoint: ${MOMO_API_ENDPOINT}
    redirect-url: ${MOMO_REDIRECT_URL}
    ipn-url: ${MOMO_IPN_URL}

  vnpay:
    tmn-code: ${VNP_TMN_CODE}
    hash-secret: ${VNP_HASH_SECRET}
    url: ${VNP_URL}
    return-url: ${VNP_RETURN_URL}